spring.application.name=CampusEats


spring.datasource.url=jdbc:h2:mem:campuseats
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true


spring.jackson.time-zone=America/Lima



jwt.secret=campuseats-secreto-super-largo-1234567890-abcdef

jwt.expiration-access=3600000
